[package]
name = "mysql-format"
version = "0.1.1"
authors = ["Brian Leishman <brian@stumpyinc.com>"]
edition = '2018'

[lib]
crate-type = ["cdylib"]

[dependencies]
time = "0.1"
phf = "0.7"
wasm-bindgen = "0.2"

[build-dependencies]
phf_codegen = "0.7"