[package]
name = "mysql-format"
version = "0.1.1"
authors = ["Brian Leishman <brian@stumpyinc.com>"]
edition = '2018'

[dependencies]
time = "0.1"
phf = "0.7"
lambda_runtime = "0.4.1"

tokio = "1.15.0"

[build-dependencies]
phf_codegen = "0.7"