[package]
name = "mysql-format"
version = "0.1.1"
authors = ["Brian Leishman <brian@stumpyinc.com>"]
edition = '2021'

[lib]
crate-type = ["cdylib"]

[dependencies]
phf = "0.11"
wasm-bindgen = "0.2.100"

[build-dependencies]
phf_codegen = "0.11"
