name: publish

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout master
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: set up rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true

      - name: install arm64 cc
        run: sudo apt install -y gcc-aarch64-linux-gnu

      - name: change linker for cargo
        run: |
          echo '[target.aarch64-unknown-linux-gnu]'  > ~/.cargo/config
          echo 'linker = "aarch64-linux-gnu-gcc"'   >> ~/.cargo/config

      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target aarch64-unknown-linux-gnu
     
      - name: zip
        run: cp ./target/aarch64-unknown-linux-gnu/release/mysql-format ./bootstrap && zip lambda.zip bootstrap && rm bootstrap

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: deploy lambda
        run: aws lambda update-function-code --function-name mysqlFormat --zip-file fileb://lambda.zip