name: publish

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

     - name: checkout master
       uses: actions/checkout@v2
       with:
        ref: ${{ github.head_ref }}

     - name: set up rust toolchain
       uses: actions-rs/toolchain@v1
       with:
         toolchain: table
         target: aarch64-unknown-linux-gnu
         override: true

     - name: build
       uses: actions-rs/cargo@v1
       with:
         command: build
         args: --release --target aarch64-unknown-linux-gnu
     
     - name: zip
       run: cp ./target/aarch64-unknown-linux-gnu/release/mysql-format ./bootstrap && zip lambda.zip bootstrap && rm bootstrap

     - name: configure aws credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: deploy lambda
        run: aws lambda update-function-code --function-name mysqlFormat --zip-file fileb://lambda.zip